// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: atleta.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAtletas = `-- name: CountAtletas :one
SELECT COUNT(*)
FROM atletas
WHERE deletado_em IS NULL
  AND ($1::text   IS NULL OR nome   ILIKE '%' || $1   || '%')
  AND ($2::text IS NULL OR status = $2)
`

type CountAtletasParams struct {
	Nome   *string `db:"nome" json:"nome"`
	Status *string `db:"status" json:"status"`
}

func (q *Queries) CountAtletas(ctx context.Context, arg CountAtletasParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAtletas, arg.Nome, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAtletaByCPF = `-- name: GetAtletaByCPF :one
SELECT id, nome, data_nascimento, cpf, rg, endereco, cidade, uf, cep, email, telefone, status, usuario_responsavel_id, criado_em, atualizado_em, deletado_em
FROM atletas
WHERE cpf = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetAtletaByCPF(ctx context.Context, cpf *string) (Atleta, error) {
	row := q.db.QueryRow(ctx, getAtletaByCPF, cpf)
	var i Atleta
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.DataNascimento,
		&i.Cpf,
		&i.Rg,
		&i.Endereco,
		&i.Cidade,
		&i.Uf,
		&i.Cep,
		&i.Email,
		&i.Telefone,
		&i.Status,
		&i.UsuarioResponsavelID,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getAtletaByID = `-- name: GetAtletaByID :one
SELECT id, nome, data_nascimento, cpf, rg, endereco, cidade, uf, cep, email, telefone, status, usuario_responsavel_id, criado_em, atualizado_em, deletado_em
FROM atletas
WHERE id = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetAtletaByID(ctx context.Context, id uuid.UUID) (Atleta, error) {
	row := q.db.QueryRow(ctx, getAtletaByID, id)
	var i Atleta
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.DataNascimento,
		&i.Cpf,
		&i.Rg,
		&i.Endereco,
		&i.Cidade,
		&i.Uf,
		&i.Cep,
		&i.Email,
		&i.Telefone,
		&i.Status,
		&i.UsuarioResponsavelID,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listAtletas = `-- name: ListAtletas :many
SELECT id, nome, data_nascimento, cpf, rg, endereco, cidade, uf, cep, email, telefone, status, usuario_responsavel_id, criado_em, atualizado_em, deletado_em
FROM atletas
WHERE deletado_em IS NULL
  AND ($1::text   IS NULL OR nome   ILIKE '%' || $1   || '%')
  AND ($2::text IS NULL OR status = $2)
ORDER BY nome
LIMIT  $4
OFFSET $3
`

type ListAtletasParams struct {
	Nome   *string `db:"nome" json:"nome"`
	Status *string `db:"status" json:"status"`
	Off    int32   `db:"off" json:"off"`
	Lim    int32   `db:"lim" json:"lim"`
}

func (q *Queries) ListAtletas(ctx context.Context, arg ListAtletasParams) ([]Atleta, error) {
	rows, err := q.db.Query(ctx, listAtletas,
		arg.Nome,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Atleta{}
	for rows.Next() {
		var i Atleta
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.DataNascimento,
			&i.Cpf,
			&i.Rg,
			&i.Endereco,
			&i.Cidade,
			&i.Uf,
			&i.Cep,
			&i.Email,
			&i.Telefone,
			&i.Status,
			&i.UsuarioResponsavelID,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAtleta = `-- name: SoftDeleteAtleta :exec
UPDATE atletas
SET
    deletado_em   = NOW(),
    status        = 'INATIVO',
    atualizado_em = NOW()
WHERE id = $1
  AND deletado_em IS NULL
`

func (q *Queries) SoftDeleteAtleta(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAtleta, id)
	return err
}

const upsertAtleta = `-- name: UpsertAtleta :one
INSERT INTO atletas (
    id, nome, data_nascimento, cpf, rg,
    endereco, cidade, uf, cep,
    email, telefone, status, usuario_responsavel_id,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    nome                   = EXCLUDED.nome,
    data_nascimento        = EXCLUDED.data_nascimento,
    cpf                    = EXCLUDED.cpf,
    rg                     = EXCLUDED.rg,
    endereco               = EXCLUDED.endereco,
    cidade                 = EXCLUDED.cidade,
    uf                     = EXCLUDED.uf,
    cep                    = EXCLUDED.cep,
    email                  = EXCLUDED.email,
    telefone               = EXCLUDED.telefone,
    status                 = EXCLUDED.status,
    usuario_responsavel_id = EXCLUDED.usuario_responsavel_id,
    atualizado_em          = NOW()
RETURNING id, nome, data_nascimento, cpf, rg, endereco, cidade, uf, cep, email, telefone, status, usuario_responsavel_id, criado_em, atualizado_em, deletado_em
`

type UpsertAtletaParams struct {
	ID                   uuid.UUID  `db:"id" json:"id"`
	Nome                 string     `db:"nome" json:"nome"`
	DataNascimento       time.Time  `db:"data_nascimento" json:"data_nascimento"`
	Cpf                  *string    `db:"cpf" json:"cpf"`
	Rg                   *string    `db:"rg" json:"rg"`
	Endereco             *string    `db:"endereco" json:"endereco"`
	Cidade               *string    `db:"cidade" json:"cidade"`
	Uf                   *string    `db:"uf" json:"uf"`
	Cep                  *string    `db:"cep" json:"cep"`
	Email                *string    `db:"email" json:"email"`
	Telefone             *string    `db:"telefone" json:"telefone"`
	Status               string     `db:"status" json:"status"`
	UsuarioResponsavelID *uuid.UUID `db:"usuario_responsavel_id" json:"usuario_responsavel_id"`
}

func (q *Queries) UpsertAtleta(ctx context.Context, arg UpsertAtletaParams) (Atleta, error) {
	row := q.db.QueryRow(ctx, upsertAtleta,
		arg.ID,
		arg.Nome,
		arg.DataNascimento,
		arg.Cpf,
		arg.Rg,
		arg.Endereco,
		arg.Cidade,
		arg.Uf,
		arg.Cep,
		arg.Email,
		arg.Telefone,
		arg.Status,
		arg.UsuarioResponsavelID,
	)
	var i Atleta
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.DataNascimento,
		&i.Cpf,
		&i.Rg,
		&i.Endereco,
		&i.Cidade,
		&i.Uf,
		&i.Cep,
		&i.Email,
		&i.Telefone,
		&i.Status,
		&i.UsuarioResponsavelID,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
