// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: campo.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countCampos = `-- name: CountCampos :one
SELECT COUNT(*)
FROM campos
WHERE ($1::text  IS NULL OR nome ILIKE '%' || $1 || '%')
  AND ($2::bool IS NULL OR ativo = $2)
`

type CountCamposParams struct {
	Nome  *string `db:"nome" json:"nome"`
	Ativo *bool   `db:"ativo" json:"ativo"`
}

func (q *Queries) CountCampos(ctx context.Context, arg CountCamposParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCampos, arg.Nome, arg.Ativo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCampoByID = `-- name: GetCampoByID :one
SELECT id, nome, endereco, capacidade_max, ativo
FROM campos
WHERE id = $1
`

func (q *Queries) GetCampoByID(ctx context.Context, id uuid.UUID) (Campo, error) {
	row := q.db.QueryRow(ctx, getCampoByID, id)
	var i Campo
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Endereco,
		&i.CapacidadeMax,
		&i.Ativo,
	)
	return i, err
}

const listCampos = `-- name: ListCampos :many
SELECT id, nome, endereco, capacidade_max, ativo
FROM campos
WHERE ($1::text  IS NULL OR nome ILIKE '%' || $1 || '%')
  AND ($2::bool IS NULL OR ativo = $2)
ORDER BY nome
LIMIT  $4
OFFSET $3
`

type ListCamposParams struct {
	Nome  *string `db:"nome" json:"nome"`
	Ativo *bool   `db:"ativo" json:"ativo"`
	Off   int32   `db:"off" json:"off"`
	Lim   int32   `db:"lim" json:"lim"`
}

func (q *Queries) ListCampos(ctx context.Context, arg ListCamposParams) ([]Campo, error) {
	rows, err := q.db.Query(ctx, listCampos,
		arg.Nome,
		arg.Ativo,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campo{}
	for rows.Next() {
		var i Campo
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Endereco,
			&i.CapacidadeMax,
			&i.Ativo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCampo = `-- name: UpsertCampo :one
INSERT INTO campos (id, nome, endereco, capacidade_max, ativo)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    nome           = EXCLUDED.nome,
    endereco       = EXCLUDED.endereco,
    capacidade_max = EXCLUDED.capacidade_max,
    ativo          = EXCLUDED.ativo
RETURNING id, nome, endereco, capacidade_max, ativo
`

type UpsertCampoParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Nome          string    `db:"nome" json:"nome"`
	Endereco      *string   `db:"endereco" json:"endereco"`
	CapacidadeMax *int32    `db:"capacidade_max" json:"capacidade_max"`
	Ativo         bool      `db:"ativo" json:"ativo"`
}

func (q *Queries) UpsertCampo(ctx context.Context, arg UpsertCampoParams) (Campo, error) {
	row := q.db.QueryRow(ctx, upsertCampo,
		arg.ID,
		arg.Nome,
		arg.Endereco,
		arg.CapacidadeMax,
		arg.Ativo,
	)
	var i Campo
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Endereco,
		&i.CapacidadeMax,
		&i.Ativo,
	)
	return i, err
}
