// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contrato.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getContratoAtivoPorAtleta = `-- name: GetContratoAtivoPorAtleta :one
SELECT id, atleta_id, plano_id, data_inicio, data_fim, valor_contratado, status, criado_em, atualizado_em
FROM contratos
WHERE atleta_id = $1
  AND status    = 'ATIVO'
LIMIT 1
`

func (q *Queries) GetContratoAtivoPorAtleta(ctx context.Context, atletaID uuid.UUID) (Contrato, error) {
	row := q.db.QueryRow(ctx, getContratoAtivoPorAtleta, atletaID)
	var i Contrato
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.PlanoID,
		&i.DataInicio,
		&i.DataFim,
		&i.ValorContratado,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getContratoByID = `-- name: GetContratoByID :one
SELECT id, atleta_id, plano_id, data_inicio, data_fim, valor_contratado, status, criado_em, atualizado_em
FROM contratos
WHERE id = $1
`

func (q *Queries) GetContratoByID(ctx context.Context, id uuid.UUID) (Contrato, error) {
	row := q.db.QueryRow(ctx, getContratoByID, id)
	var i Contrato
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.PlanoID,
		&i.DataInicio,
		&i.DataFim,
		&i.ValorContratado,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listContratosAtivos = `-- name: ListContratosAtivos :many
SELECT c.id, c.atleta_id, c.plano_id, c.data_inicio, c.data_fim, c.valor_contratado, c.status, c.criado_em, c.atualizado_em, p.dia_vencimento
FROM contratos c
JOIN planos    p ON p.id = c.plano_id
WHERE c.status = 'ATIVO'
`

type ListContratosAtivosRow struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	AtletaID        uuid.UUID       `db:"atleta_id" json:"atleta_id"`
	PlanoID         uuid.UUID       `db:"plano_id" json:"plano_id"`
	DataInicio      time.Time       `db:"data_inicio" json:"data_inicio"`
	DataFim         *time.Time      `db:"data_fim" json:"data_fim"`
	ValorContratado decimal.Decimal `db:"valor_contratado" json:"valor_contratado"`
	Status          string          `db:"status" json:"status"`
	CriadoEm        time.Time       `db:"criado_em" json:"criado_em"`
	AtualizadoEm    time.Time       `db:"atualizado_em" json:"atualizado_em"`
	DiaVencimento   int32           `db:"dia_vencimento" json:"dia_vencimento"`
}

func (q *Queries) ListContratosAtivos(ctx context.Context) ([]ListContratosAtivosRow, error) {
	rows, err := q.db.Query(ctx, listContratosAtivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContratosAtivosRow{}
	for rows.Next() {
		var i ListContratosAtivosRow
		if err := rows.Scan(
			&i.ID,
			&i.AtletaID,
			&i.PlanoID,
			&i.DataInicio,
			&i.DataFim,
			&i.ValorContratado,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DiaVencimento,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContrato = `-- name: UpsertContrato :one
INSERT INTO contratos (
    id, atleta_id, plano_id,
    data_inicio, data_fim, valor_contratado, status,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    data_fim         = EXCLUDED.data_fim,
    valor_contratado = EXCLUDED.valor_contratado,
    status           = EXCLUDED.status,
    atualizado_em    = NOW()
RETURNING id, atleta_id, plano_id, data_inicio, data_fim, valor_contratado, status, criado_em, atualizado_em
`

type UpsertContratoParams struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	AtletaID        uuid.UUID       `db:"atleta_id" json:"atleta_id"`
	PlanoID         uuid.UUID       `db:"plano_id" json:"plano_id"`
	DataInicio      time.Time       `db:"data_inicio" json:"data_inicio"`
	DataFim         *time.Time      `db:"data_fim" json:"data_fim"`
	ValorContratado decimal.Decimal `db:"valor_contratado" json:"valor_contratado"`
	Status          string          `db:"status" json:"status"`
}

func (q *Queries) UpsertContrato(ctx context.Context, arg UpsertContratoParams) (Contrato, error) {
	row := q.db.QueryRow(ctx, upsertContrato,
		arg.ID,
		arg.AtletaID,
		arg.PlanoID,
		arg.DataInicio,
		arg.DataFim,
		arg.ValorContratado,
		arg.Status,
	)
	var i Contrato
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.PlanoID,
		&i.DataInicio,
		&i.DataFim,
		&i.ValorContratado,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
