// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: frequencia.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listFrequenciasPorTreino = `-- name: ListFrequenciasPorTreino :many
SELECT id, treino_id, atleta_id, presenca, justificativa, registrado_em
FROM frequencias
WHERE treino_id = $1
ORDER BY registrado_em
`

func (q *Queries) ListFrequenciasPorTreino(ctx context.Context, treinoID uuid.UUID) ([]Frequencia, error) {
	rows, err := q.db.Query(ctx, listFrequenciasPorTreino, treinoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Frequencia{}
	for rows.Next() {
		var i Frequencia
		if err := rows.Scan(
			&i.ID,
			&i.TreinoID,
			&i.AtletaID,
			&i.Presenca,
			&i.Justificativa,
			&i.RegistradoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFrequencia = `-- name: UpsertFrequencia :one
INSERT INTO frequencias (
    id, treino_id, atleta_id, presenca, justificativa, registrado_em
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (treino_id, atleta_id) DO UPDATE SET
    presenca      = EXCLUDED.presenca,
    justificativa = EXCLUDED.justificativa,
    registrado_em = NOW()
RETURNING id, treino_id, atleta_id, presenca, justificativa, registrado_em
`

type UpsertFrequenciaParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	TreinoID      uuid.UUID `db:"treino_id" json:"treino_id"`
	AtletaID      uuid.UUID `db:"atleta_id" json:"atleta_id"`
	Presenca      string    `db:"presenca" json:"presenca"`
	Justificativa *string   `db:"justificativa" json:"justificativa"`
}

func (q *Queries) UpsertFrequencia(ctx context.Context, arg UpsertFrequenciaParams) (Frequencia, error) {
	row := q.db.QueryRow(ctx, upsertFrequencia,
		arg.ID,
		arg.TreinoID,
		arg.AtletaID,
		arg.Presenca,
		arg.Justificativa,
	)
	var i Frequencia
	err := row.Scan(
		&i.ID,
		&i.TreinoID,
		&i.AtletaID,
		&i.Presenca,
		&i.Justificativa,
		&i.RegistradoEm,
	)
	return i, err
}
