// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: matricula.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMatriculasAtivasPorTurma = `-- name: CountMatriculasAtivasPorTurma :one
SELECT COUNT(*)
FROM matriculas
WHERE turma_id = $1
  AND status   = 'ATIVA'
`

func (q *Queries) CountMatriculasAtivasPorTurma(ctx context.Context, turmaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMatriculasAtivasPorTurma, turmaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatriculasPorTurma = `-- name: CountMatriculasPorTurma :one
SELECT COUNT(*)
FROM matriculas
WHERE turma_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountMatriculasPorTurmaParams struct {
	TurmaID uuid.UUID `db:"turma_id" json:"turma_id"`
	Status  *string   `db:"status" json:"status"`
}

func (q *Queries) CountMatriculasPorTurma(ctx context.Context, arg CountMatriculasPorTurmaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatriculasPorTurma, arg.TurmaID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMatriculaAtivaByAtletaTurma = `-- name: GetMatriculaAtivaByAtletaTurma :one
SELECT id, atleta_id, turma_id, data_inicio, data_fim, status, criado_em, atualizado_em
FROM matriculas
WHERE atleta_id = $1
  AND turma_id  = $2
  AND status    = 'ATIVA'
LIMIT 1
`

type GetMatriculaAtivaByAtletaTurmaParams struct {
	AtletaID uuid.UUID `db:"atleta_id" json:"atleta_id"`
	TurmaID  uuid.UUID `db:"turma_id" json:"turma_id"`
}

func (q *Queries) GetMatriculaAtivaByAtletaTurma(ctx context.Context, arg GetMatriculaAtivaByAtletaTurmaParams) (Matricula, error) {
	row := q.db.QueryRow(ctx, getMatriculaAtivaByAtletaTurma, arg.AtletaID, arg.TurmaID)
	var i Matricula
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.TurmaID,
		&i.DataInicio,
		&i.DataFim,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getMatriculaByID = `-- name: GetMatriculaByID :one
SELECT id, atleta_id, turma_id, data_inicio, data_fim, status, criado_em, atualizado_em
FROM matriculas
WHERE id = $1
`

func (q *Queries) GetMatriculaByID(ctx context.Context, id uuid.UUID) (Matricula, error) {
	row := q.db.QueryRow(ctx, getMatriculaByID, id)
	var i Matricula
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.TurmaID,
		&i.DataInicio,
		&i.DataFim,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listMatriculasPorTurma = `-- name: ListMatriculasPorTurma :many
SELECT id, atleta_id, turma_id, data_inicio, data_fim, status, criado_em, atualizado_em
FROM matriculas
WHERE turma_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY criado_em DESC
LIMIT  $4
OFFSET $3
`

type ListMatriculasPorTurmaParams struct {
	TurmaID uuid.UUID `db:"turma_id" json:"turma_id"`
	Status  *string   `db:"status" json:"status"`
	Off     int32     `db:"off" json:"off"`
	Lim     int32     `db:"lim" json:"lim"`
}

func (q *Queries) ListMatriculasPorTurma(ctx context.Context, arg ListMatriculasPorTurmaParams) ([]Matricula, error) {
	rows, err := q.db.Query(ctx, listMatriculasPorTurma,
		arg.TurmaID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Matricula{}
	for rows.Next() {
		var i Matricula
		if err := rows.Scan(
			&i.ID,
			&i.AtletaID,
			&i.TurmaID,
			&i.DataInicio,
			&i.DataFim,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatricula = `-- name: UpsertMatricula :one
INSERT INTO matriculas (
    id, atleta_id, turma_id, data_inicio, data_fim, status,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5, $6,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    data_fim      = EXCLUDED.data_fim,
    status        = EXCLUDED.status,
    atualizado_em = NOW()
RETURNING id, atleta_id, turma_id, data_inicio, data_fim, status, criado_em, atualizado_em
`

type UpsertMatriculaParams struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	AtletaID   uuid.UUID  `db:"atleta_id" json:"atleta_id"`
	TurmaID    uuid.UUID  `db:"turma_id" json:"turma_id"`
	DataInicio time.Time  `db:"data_inicio" json:"data_inicio"`
	DataFim    *time.Time `db:"data_fim" json:"data_fim"`
	Status     string     `db:"status" json:"status"`
}

func (q *Queries) UpsertMatricula(ctx context.Context, arg UpsertMatriculaParams) (Matricula, error) {
	row := q.db.QueryRow(ctx, upsertMatricula,
		arg.ID,
		arg.AtletaID,
		arg.TurmaID,
		arg.DataInicio,
		arg.DataFim,
		arg.Status,
	)
	var i Matricula
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.TurmaID,
		&i.DataInicio,
		&i.DataFim,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
