// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mensalidade.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/shopspring/decimal"
)

const countMensalidades = `-- name: CountMensalidades :one
SELECT COUNT(*)
FROM mensalidades
WHERE ($1::uuid IS NULL OR atleta_id = $1)
  AND ($2::text    IS NULL OR status    = $2)
  AND ($3::int   IS NULL OR competencia_ano = $3)
  AND ($4::int   IS NULL OR competencia_mes = $4)
`

type CountMensalidadesParams struct {
	AtletaID *uuid.UUID `db:"atleta_id" json:"atleta_id"`
	Status   *string    `db:"status" json:"status"`
	CompAno  *int32     `db:"comp_ano" json:"comp_ano"`
	CompMes  *int32     `db:"comp_mes" json:"comp_mes"`
}

func (q *Queries) CountMensalidades(ctx context.Context, arg CountMensalidadesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMensalidades,
		arg.AtletaID,
		arg.Status,
		arg.CompAno,
		arg.CompMes,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMensalidadeByContratoCompetencia = `-- name: GetMensalidadeByContratoCompetencia :one
SELECT id, contrato_id, atleta_id, competencia_ano, competencia_mes, data_vencimento, valor, valor_pago, status, data_pagamento, forma_pagamento, observacao, criado_em, atualizado_em
FROM mensalidades
WHERE contrato_id = $1
  AND competencia_ano = $2
  AND competencia_mes = $3
`

type GetMensalidadeByContratoCompetenciaParams struct {
	ContratoID     uuid.UUID `db:"contrato_id" json:"contrato_id"`
	CompetenciaAno int32     `db:"competencia_ano" json:"competencia_ano"`
	CompetenciaMes int32     `db:"competencia_mes" json:"competencia_mes"`
}

func (q *Queries) GetMensalidadeByContratoCompetencia(ctx context.Context, arg GetMensalidadeByContratoCompetenciaParams) (Mensalidade, error) {
	row := q.db.QueryRow(ctx, getMensalidadeByContratoCompetencia, arg.ContratoID, arg.CompetenciaAno, arg.CompetenciaMes)
	var i Mensalidade
	err := row.Scan(
		&i.ID,
		&i.ContratoID,
		&i.AtletaID,
		&i.CompetenciaAno,
		&i.CompetenciaMes,
		&i.DataVencimento,
		&i.Valor,
		&i.ValorPago,
		&i.Status,
		&i.DataPagamento,
		&i.FormaPagamento,
		&i.Observacao,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getMensalidadeByID = `-- name: GetMensalidadeByID :one
SELECT id, contrato_id, atleta_id, competencia_ano, competencia_mes, data_vencimento, valor, valor_pago, status, data_pagamento, forma_pagamento, observacao, criado_em, atualizado_em
FROM mensalidades
WHERE id = $1
`

func (q *Queries) GetMensalidadeByID(ctx context.Context, id uuid.UUID) (Mensalidade, error) {
	row := q.db.QueryRow(ctx, getMensalidadeByID, id)
	var i Mensalidade
	err := row.Scan(
		&i.ID,
		&i.ContratoID,
		&i.AtletaID,
		&i.CompetenciaAno,
		&i.CompetenciaMes,
		&i.DataVencimento,
		&i.Valor,
		&i.ValorPago,
		&i.Status,
		&i.DataPagamento,
		&i.FormaPagamento,
		&i.Observacao,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const insertMensalidade = `-- name: InsertMensalidade :one
INSERT INTO mensalidades (
    id, contrato_id, atleta_id,
    competencia_ano, competencia_mes,
    data_vencimento, valor, status,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    NOW(), NOW()
)
RETURNING id, contrato_id, atleta_id, competencia_ano, competencia_mes, data_vencimento, valor, valor_pago, status, data_pagamento, forma_pagamento, observacao, criado_em, atualizado_em
`

type InsertMensalidadeParams struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	ContratoID     uuid.UUID       `db:"contrato_id" json:"contrato_id"`
	AtletaID       uuid.UUID       `db:"atleta_id" json:"atleta_id"`
	CompetenciaAno int32           `db:"competencia_ano" json:"competencia_ano"`
	CompetenciaMes int32           `db:"competencia_mes" json:"competencia_mes"`
	DataVencimento time.Time       `db:"data_vencimento" json:"data_vencimento"`
	Valor          decimal.Decimal `db:"valor" json:"valor"`
	Status         string          `db:"status" json:"status"`
}

func (q *Queries) InsertMensalidade(ctx context.Context, arg InsertMensalidadeParams) (Mensalidade, error) {
	row := q.db.QueryRow(ctx, insertMensalidade,
		arg.ID,
		arg.ContratoID,
		arg.AtletaID,
		arg.CompetenciaAno,
		arg.CompetenciaMes,
		arg.DataVencimento,
		arg.Valor,
		arg.Status,
	)
	var i Mensalidade
	err := row.Scan(
		&i.ID,
		&i.ContratoID,
		&i.AtletaID,
		&i.CompetenciaAno,
		&i.CompetenciaMes,
		&i.DataVencimento,
		&i.Valor,
		&i.ValorPago,
		&i.Status,
		&i.DataPagamento,
		&i.FormaPagamento,
		&i.Observacao,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listMensalidades = `-- name: ListMensalidades :many
SELECT id, contrato_id, atleta_id, competencia_ano, competencia_mes, data_vencimento, valor, valor_pago, status, data_pagamento, forma_pagamento, observacao, criado_em, atualizado_em
FROM mensalidades
WHERE ($1::uuid   IS NULL OR atleta_id = $1)
  AND ($2::text      IS NULL OR status    = $2)
  AND ($3::int     IS NULL OR competencia_ano = $3)
  AND ($4::int     IS NULL OR competencia_mes = $4)
ORDER BY data_vencimento
LIMIT  $6
OFFSET $5
`

type ListMensalidadesParams struct {
	AtletaID *uuid.UUID `db:"atleta_id" json:"atleta_id"`
	Status   *string    `db:"status" json:"status"`
	CompAno  *int32     `db:"comp_ano" json:"comp_ano"`
	CompMes  *int32     `db:"comp_mes" json:"comp_mes"`
	Off      int32      `db:"off" json:"off"`
	Lim      int32      `db:"lim" json:"lim"`
}

func (q *Queries) ListMensalidades(ctx context.Context, arg ListMensalidadesParams) ([]Mensalidade, error) {
	rows, err := q.db.Query(ctx, listMensalidades,
		arg.AtletaID,
		arg.Status,
		arg.CompAno,
		arg.CompMes,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mensalidade{}
	for rows.Next() {
		var i Mensalidade
		if err := rows.Scan(
			&i.ID,
			&i.ContratoID,
			&i.AtletaID,
			&i.CompetenciaAno,
			&i.CompetenciaMes,
			&i.DataVencimento,
			&i.Valor,
			&i.ValorPago,
			&i.Status,
			&i.DataPagamento,
			&i.FormaPagamento,
			&i.Observacao,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarMensalidadesVencidas = `-- name: MarcarMensalidadesVencidas :execresult
UPDATE mensalidades
SET
    status        = 'VENCIDO',
    atualizado_em = NOW()
WHERE status          = 'PENDENTE'
  AND data_vencimento < CURRENT_DATE
`

func (q *Queries) MarcarMensalidadesVencidas(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, marcarMensalidadesVencidas)
}

const updateMensalidadePagamento = `-- name: UpdateMensalidadePagamento :one
UPDATE mensalidades
SET
    status          = 'PAGO',
    valor_pago      = $2,
    data_pagamento  = $3,
    forma_pagamento = $4,
    observacao      = $5,
    atualizado_em   = NOW()
WHERE id = $1
RETURNING id, contrato_id, atleta_id, competencia_ano, competencia_mes, data_vencimento, valor, valor_pago, status, data_pagamento, forma_pagamento, observacao, criado_em, atualizado_em
`

type UpdateMensalidadePagamentoParams struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	ValorPago      *decimal.Decimal `db:"valor_pago" json:"valor_pago"`
	DataPagamento  *time.Time       `db:"data_pagamento" json:"data_pagamento"`
	FormaPagamento *string          `db:"forma_pagamento" json:"forma_pagamento"`
	Observacao     *string          `db:"observacao" json:"observacao"`
}

func (q *Queries) UpdateMensalidadePagamento(ctx context.Context, arg UpdateMensalidadePagamentoParams) (Mensalidade, error) {
	row := q.db.QueryRow(ctx, updateMensalidadePagamento,
		arg.ID,
		arg.ValorPago,
		arg.DataPagamento,
		arg.FormaPagamento,
		arg.Observacao,
	)
	var i Mensalidade
	err := row.Scan(
		&i.ID,
		&i.ContratoID,
		&i.AtletaID,
		&i.CompetenciaAno,
		&i.CompetenciaMes,
		&i.DataVencimento,
		&i.Valor,
		&i.ValorPago,
		&i.Status,
		&i.DataPagamento,
		&i.FormaPagamento,
		&i.Observacao,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateMensalidadeStatus = `-- name: UpdateMensalidadeStatus :one
UPDATE mensalidades
SET
    status        = $2,
    atualizado_em = NOW()
WHERE id = $1
RETURNING id, contrato_id, atleta_id, competencia_ano, competencia_mes, data_vencimento, valor, valor_pago, status, data_pagamento, forma_pagamento, observacao, criado_em, atualizado_em
`

type UpdateMensalidadeStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateMensalidadeStatus(ctx context.Context, arg UpdateMensalidadeStatusParams) (Mensalidade, error) {
	row := q.db.QueryRow(ctx, updateMensalidadeStatus, arg.ID, arg.Status)
	var i Mensalidade
	err := row.Scan(
		&i.ID,
		&i.ContratoID,
		&i.AtletaID,
		&i.CompetenciaAno,
		&i.CompetenciaMes,
		&i.DataVencimento,
		&i.Valor,
		&i.ValorPago,
		&i.Status,
		&i.DataPagamento,
		&i.FormaPagamento,
		&i.Observacao,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
