// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type DiaSemana string

const (
	DiaSemanaSEG DiaSemana = "SEG"
	DiaSemanaTER DiaSemana = "TER"
	DiaSemanaQUA DiaSemana = "QUA"
	DiaSemanaQUI DiaSemana = "QUI"
	DiaSemanaSEX DiaSemana = "SEX"
	DiaSemanaSAB DiaSemana = "SAB"
	DiaSemanaDOM DiaSemana = "DOM"
)

func (e *DiaSemana) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiaSemana(s)
	case string:
		*e = DiaSemana(s)
	default:
		return fmt.Errorf("unsupported scan type for DiaSemana: %T", src)
	}
	return nil
}

type NullDiaSemana struct {
	DiaSemana DiaSemana `json:"dia_semana"`
	Valid     bool      `json:"valid"` // Valid is true if DiaSemana is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiaSemana) Scan(value interface{}) error {
	if value == nil {
		ns.DiaSemana, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiaSemana.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiaSemana) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiaSemana), nil
}

type Parentesco string

const (
	ParentescoPAI   Parentesco = "PAI"
	ParentescoMAE   Parentesco = "MAE"
	ParentescoAVO   Parentesco = "AVO"
	ParentescoOUTRO Parentesco = "OUTRO"
)

func (e *Parentesco) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Parentesco(s)
	case string:
		*e = Parentesco(s)
	default:
		return fmt.Errorf("unsupported scan type for Parentesco: %T", src)
	}
	return nil
}

type NullParentesco struct {
	Parentesco Parentesco `json:"parentesco"`
	Valid      bool       `json:"valid"` // Valid is true if Parentesco is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParentesco) Scan(value interface{}) error {
	if value == nil {
		ns.Parentesco, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Parentesco.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParentesco) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Parentesco), nil
}

type PerfilUsuario string

const (
	PerfilUsuarioADMIN       PerfilUsuario = "ADMIN"
	PerfilUsuarioTREINADOR   PerfilUsuario = "TREINADOR"
	PerfilUsuarioRESPONSAVEL PerfilUsuario = "RESPONSAVEL"
)

func (e *PerfilUsuario) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PerfilUsuario(s)
	case string:
		*e = PerfilUsuario(s)
	default:
		return fmt.Errorf("unsupported scan type for PerfilUsuario: %T", src)
	}
	return nil
}

type NullPerfilUsuario struct {
	PerfilUsuario PerfilUsuario `json:"perfil_usuario"`
	Valid         bool          `json:"valid"` // Valid is true if PerfilUsuario is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPerfilUsuario) Scan(value interface{}) error {
	if value == nil {
		ns.PerfilUsuario, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PerfilUsuario.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPerfilUsuario) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PerfilUsuario), nil
}

type Presenca string

const (
	PresencaPRESENTE    Presenca = "PRESENTE"
	PresencaAUSENTE     Presenca = "AUSENTE"
	PresencaJUSTIFICADO Presenca = "JUSTIFICADO"
)

func (e *Presenca) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Presenca(s)
	case string:
		*e = Presenca(s)
	default:
		return fmt.Errorf("unsupported scan type for Presenca: %T", src)
	}
	return nil
}

type NullPresenca struct {
	Presenca Presenca `json:"presenca"`
	Valid    bool     `json:"valid"` // Valid is true if Presenca is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPresenca) Scan(value interface{}) error {
	if value == nil {
		ns.Presenca, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Presenca.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPresenca) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Presenca), nil
}

type StatusAtleta string

const (
	StatusAtletaATIVO    StatusAtleta = "ATIVO"
	StatusAtletaINATIVO  StatusAtleta = "INATIVO"
	StatusAtletaSUSPENSO StatusAtleta = "SUSPENSO"
)

func (e *StatusAtleta) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusAtleta(s)
	case string:
		*e = StatusAtleta(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusAtleta: %T", src)
	}
	return nil
}

type NullStatusAtleta struct {
	StatusAtleta StatusAtleta `json:"status_atleta"`
	Valid        bool         `json:"valid"` // Valid is true if StatusAtleta is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusAtleta) Scan(value interface{}) error {
	if value == nil {
		ns.StatusAtleta, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusAtleta.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusAtleta) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusAtleta), nil
}

type StatusContrato string

const (
	StatusContratoATIVO     StatusContrato = "ATIVO"
	StatusContratoCANCELADO StatusContrato = "CANCELADO"
	StatusContratoENCERRADO StatusContrato = "ENCERRADO"
)

func (e *StatusContrato) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusContrato(s)
	case string:
		*e = StatusContrato(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusContrato: %T", src)
	}
	return nil
}

type NullStatusContrato struct {
	StatusContrato StatusContrato `json:"status_contrato"`
	Valid          bool           `json:"valid"` // Valid is true if StatusContrato is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusContrato) Scan(value interface{}) error {
	if value == nil {
		ns.StatusContrato, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusContrato.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusContrato) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusContrato), nil
}

type StatusMatricula string

const (
	StatusMatriculaATIVA       StatusMatricula = "ATIVA"
	StatusMatriculaCANCELADA   StatusMatricula = "CANCELADA"
	StatusMatriculaTRANSFERIDA StatusMatricula = "TRANSFERIDA"
)

func (e *StatusMatricula) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusMatricula(s)
	case string:
		*e = StatusMatricula(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusMatricula: %T", src)
	}
	return nil
}

type NullStatusMatricula struct {
	StatusMatricula StatusMatricula `json:"status_matricula"`
	Valid           bool            `json:"valid"` // Valid is true if StatusMatricula is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusMatricula) Scan(value interface{}) error {
	if value == nil {
		ns.StatusMatricula, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusMatricula.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusMatricula) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusMatricula), nil
}

type StatusMensalidade string

const (
	StatusMensalidadePENDENTE  StatusMensalidade = "PENDENTE"
	StatusMensalidadePAGO      StatusMensalidade = "PAGO"
	StatusMensalidadeVENCIDO   StatusMensalidade = "VENCIDO"
	StatusMensalidadeCANCELADO StatusMensalidade = "CANCELADO"
	StatusMensalidadeISENTO    StatusMensalidade = "ISENTO"
)

func (e *StatusMensalidade) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusMensalidade(s)
	case string:
		*e = StatusMensalidade(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusMensalidade: %T", src)
	}
	return nil
}

type NullStatusMensalidade struct {
	StatusMensalidade StatusMensalidade `json:"status_mensalidade"`
	Valid             bool              `json:"valid"` // Valid is true if StatusMensalidade is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusMensalidade) Scan(value interface{}) error {
	if value == nil {
		ns.StatusMensalidade, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusMensalidade.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusMensalidade) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusMensalidade), nil
}

type StatusTreinador string

const (
	StatusTreinadorATIVO   StatusTreinador = "ATIVO"
	StatusTreinadorINATIVO StatusTreinador = "INATIVO"
)

func (e *StatusTreinador) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusTreinador(s)
	case string:
		*e = StatusTreinador(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusTreinador: %T", src)
	}
	return nil
}

type NullStatusTreinador struct {
	StatusTreinador StatusTreinador `json:"status_treinador"`
	Valid           bool            `json:"valid"` // Valid is true if StatusTreinador is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusTreinador) Scan(value interface{}) error {
	if value == nil {
		ns.StatusTreinador, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusTreinador.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusTreinador) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusTreinador), nil
}

type StatusTurma string

const (
	StatusTurmaATIVA     StatusTurma = "ATIVA"
	StatusTurmaENCERRADA StatusTurma = "ENCERRADA"
	StatusTurmaSUSPENSA  StatusTurma = "SUSPENSA"
)

func (e *StatusTurma) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusTurma(s)
	case string:
		*e = StatusTurma(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusTurma: %T", src)
	}
	return nil
}

type NullStatusTurma struct {
	StatusTurma StatusTurma `json:"status_turma"`
	Valid       bool        `json:"valid"` // Valid is true if StatusTurma is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusTurma) Scan(value interface{}) error {
	if value == nil {
		ns.StatusTurma, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusTurma.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusTurma) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusTurma), nil
}

type Atleta struct {
	ID                   uuid.UUID  `db:"id" json:"id"`
	Nome                 string     `db:"nome" json:"nome"`
	DataNascimento       time.Time  `db:"data_nascimento" json:"data_nascimento"`
	Cpf                  *string    `db:"cpf" json:"cpf"`
	Rg                   *string    `db:"rg" json:"rg"`
	Endereco             *string    `db:"endereco" json:"endereco"`
	Cidade               *string    `db:"cidade" json:"cidade"`
	Uf                   *string    `db:"uf" json:"uf"`
	Cep                  *string    `db:"cep" json:"cep"`
	Email                *string    `db:"email" json:"email"`
	Telefone             *string    `db:"telefone" json:"telefone"`
	Status               string     `db:"status" json:"status"`
	UsuarioResponsavelID *uuid.UUID `db:"usuario_responsavel_id" json:"usuario_responsavel_id"`
	CriadoEm             time.Time  `db:"criado_em" json:"criado_em"`
	AtualizadoEm         time.Time  `db:"atualizado_em" json:"atualizado_em"`
	DeletadoEm           *time.Time `db:"deletado_em" json:"deletado_em"`
}

type Campo struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Nome          string    `db:"nome" json:"nome"`
	Endereco      *string   `db:"endereco" json:"endereco"`
	CapacidadeMax *int32    `db:"capacidade_max" json:"capacidade_max"`
	Ativo         bool      `db:"ativo" json:"ativo"`
}

type Contrato struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	AtletaID        uuid.UUID       `db:"atleta_id" json:"atleta_id"`
	PlanoID         uuid.UUID       `db:"plano_id" json:"plano_id"`
	DataInicio      time.Time       `db:"data_inicio" json:"data_inicio"`
	DataFim         *time.Time      `db:"data_fim" json:"data_fim"`
	ValorContratado decimal.Decimal `db:"valor_contratado" json:"valor_contratado"`
	Status          string          `db:"status" json:"status"`
	CriadoEm        time.Time       `db:"criado_em" json:"criado_em"`
	AtualizadoEm    time.Time       `db:"atualizado_em" json:"atualizado_em"`
}

type Frequencia struct {
	ID            uuid.UUID `db:"id" json:"id"`
	TreinoID      uuid.UUID `db:"treino_id" json:"treino_id"`
	AtletaID      uuid.UUID `db:"atleta_id" json:"atleta_id"`
	Presenca      string    `db:"presenca" json:"presenca"`
	Justificativa *string   `db:"justificativa" json:"justificativa"`
	RegistradoEm  time.Time `db:"registrado_em" json:"registrado_em"`
}

type HorariosTurma struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	TurmaID    uuid.UUID   `db:"turma_id" json:"turma_id"`
	DiaSemana  string      `db:"dia_semana" json:"dia_semana"`
	HoraInicio pgtype.Time `db:"hora_inicio" json:"hora_inicio"`
	HoraFim    pgtype.Time `db:"hora_fim" json:"hora_fim"`
}

type JobExecuco struct {
	ID          uuid.UUID `db:"id" json:"id"`
	NomeJob     string    `db:"nome_job" json:"nome_job"`
	Status      string    `db:"status" json:"status"`
	Mensagem    *string   `db:"mensagem" json:"mensagem"`
	Payload     []byte    `db:"payload" json:"payload"`
	ExecutadoEm time.Time `db:"executado_em" json:"executado_em"`
}

type Matricula struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	AtletaID     uuid.UUID  `db:"atleta_id" json:"atleta_id"`
	TurmaID      uuid.UUID  `db:"turma_id" json:"turma_id"`
	DataInicio   time.Time  `db:"data_inicio" json:"data_inicio"`
	DataFim      *time.Time `db:"data_fim" json:"data_fim"`
	Status       string     `db:"status" json:"status"`
	CriadoEm     time.Time  `db:"criado_em" json:"criado_em"`
	AtualizadoEm time.Time  `db:"atualizado_em" json:"atualizado_em"`
}

type Mensalidade struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	ContratoID     uuid.UUID        `db:"contrato_id" json:"contrato_id"`
	AtletaID       uuid.UUID        `db:"atleta_id" json:"atleta_id"`
	CompetenciaAno int32            `db:"competencia_ano" json:"competencia_ano"`
	CompetenciaMes int32            `db:"competencia_mes" json:"competencia_mes"`
	DataVencimento time.Time        `db:"data_vencimento" json:"data_vencimento"`
	Valor          decimal.Decimal  `db:"valor" json:"valor"`
	ValorPago      *decimal.Decimal `db:"valor_pago" json:"valor_pago"`
	Status         string           `db:"status" json:"status"`
	DataPagamento  *time.Time       `db:"data_pagamento" json:"data_pagamento"`
	FormaPagamento *string          `db:"forma_pagamento" json:"forma_pagamento"`
	Observacao     *string          `db:"observacao" json:"observacao"`
	CriadoEm       time.Time        `db:"criado_em" json:"criado_em"`
	AtualizadoEm   time.Time        `db:"atualizado_em" json:"atualizado_em"`
}

type Plano struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	Nome          string          `db:"nome" json:"nome"`
	DiasSemana    int32           `db:"dias_semana" json:"dias_semana"`
	ValorMensal   decimal.Decimal `db:"valor_mensal" json:"valor_mensal"`
	DiaVencimento int32           `db:"dia_vencimento" json:"dia_vencimento"`
	Ativo         bool            `db:"ativo" json:"ativo"`
	CriadoEm      time.Time       `db:"criado_em" json:"criado_em"`
	AtualizadoEm  time.Time       `db:"atualizado_em" json:"atualizado_em"`
}

type Responsavei struct {
	ID               uuid.UUID `db:"id" json:"id"`
	AtletaID         uuid.UUID `db:"atleta_id" json:"atleta_id"`
	Nome             string    `db:"nome" json:"nome"`
	Cpf              *string   `db:"cpf" json:"cpf"`
	Email            *string   `db:"email" json:"email"`
	Telefone         string    `db:"telefone" json:"telefone"`
	Parentesco       string    `db:"parentesco" json:"parentesco"`
	ContatoPrincipal bool      `db:"contato_principal" json:"contato_principal"`
	CriadoEm         time.Time `db:"criado_em" json:"criado_em"`
	AtualizadoEm     time.Time `db:"atualizado_em" json:"atualizado_em"`
}

type Treinadore struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	UsuarioID    uuid.UUID  `db:"usuario_id" json:"usuario_id"`
	Nome         string     `db:"nome" json:"nome"`
	Cpf          *string    `db:"cpf" json:"cpf"`
	Cref         *string    `db:"cref" json:"cref"`
	Telefone     *string    `db:"telefone" json:"telefone"`
	Status       string     `db:"status" json:"status"`
	CriadoEm     time.Time  `db:"criado_em" json:"criado_em"`
	AtualizadoEm time.Time  `db:"atualizado_em" json:"atualizado_em"`
	DeletadoEm   *time.Time `db:"deletado_em" json:"deletado_em"`
}

type Treino struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	TurmaID    uuid.UUID   `db:"turma_id" json:"turma_id"`
	DataTreino time.Time   `db:"data_treino" json:"data_treino"`
	HoraInicio pgtype.Time `db:"hora_inicio" json:"hora_inicio"`
	HoraFim    pgtype.Time `db:"hora_fim" json:"hora_fim"`
	Observacao *string     `db:"observacao" json:"observacao"`
	CriadoEm   time.Time   `db:"criado_em" json:"criado_em"`
}

type Turma struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	Nome           string     `db:"nome" json:"nome"`
	FaixaEtariaMin int32      `db:"faixa_etaria_min" json:"faixa_etaria_min"`
	FaixaEtariaMax int32      `db:"faixa_etaria_max" json:"faixa_etaria_max"`
	CapacidadeMax  int32      `db:"capacidade_max" json:"capacidade_max"`
	TreinadorID    *uuid.UUID `db:"treinador_id" json:"treinador_id"`
	CampoID        *uuid.UUID `db:"campo_id" json:"campo_id"`
	Status         string     `db:"status" json:"status"`
	CriadoEm       time.Time  `db:"criado_em" json:"criado_em"`
	AtualizadoEm   time.Time  `db:"atualizado_em" json:"atualizado_em"`
	DeletadoEm     *time.Time `db:"deletado_em" json:"deletado_em"`
}

type Uniforme struct {
	ID           uuid.UUID `db:"id" json:"id"`
	AtletaID     uuid.UUID `db:"atleta_id" json:"atleta_id"`
	TamCamisa    string    `db:"tam_camisa" json:"tam_camisa"`
	TamShort     string    `db:"tam_short" json:"tam_short"`
	TamChuteira  string    `db:"tam_chuteira" json:"tam_chuteira"`
	AtualizadoEm time.Time `db:"atualizado_em" json:"atualizado_em"`
}

type Usuario struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	Email        string     `db:"email" json:"email"`
	SenhaHash    string     `db:"senha_hash" json:"senha_hash"`
	Perfil       string     `db:"perfil" json:"perfil"`
	Ativo        bool       `db:"ativo" json:"ativo"`
	CriadoEm     time.Time  `db:"criado_em" json:"criado_em"`
	AtualizadoEm time.Time  `db:"atualizado_em" json:"atualizado_em"`
	DeletadoEm   *time.Time `db:"deletado_em" json:"deletado_em"`
}
