// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plano.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getPlanoByID = `-- name: GetPlanoByID :one
SELECT id, nome, dias_semana, valor_mensal, dia_vencimento, ativo, criado_em, atualizado_em
FROM planos
WHERE id = $1
`

func (q *Queries) GetPlanoByID(ctx context.Context, id uuid.UUID) (Plano, error) {
	row := q.db.QueryRow(ctx, getPlanoByID, id)
	var i Plano
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.DiasSemana,
		&i.ValorMensal,
		&i.DiaVencimento,
		&i.Ativo,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listPlanosAtivos = `-- name: ListPlanosAtivos :many
SELECT id, nome, dias_semana, valor_mensal, dia_vencimento, ativo, criado_em, atualizado_em
FROM planos
WHERE ativo = TRUE
ORDER BY valor_mensal
`

func (q *Queries) ListPlanosAtivos(ctx context.Context) ([]Plano, error) {
	rows, err := q.db.Query(ctx, listPlanosAtivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plano{}
	for rows.Next() {
		var i Plano
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.DiasSemana,
			&i.ValorMensal,
			&i.DiaVencimento,
			&i.Ativo,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlano = `-- name: UpsertPlano :one
INSERT INTO planos (
    id, nome, dias_semana, valor_mensal, dia_vencimento, ativo,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5, $6,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    nome           = EXCLUDED.nome,
    dias_semana    = EXCLUDED.dias_semana,
    valor_mensal   = EXCLUDED.valor_mensal,
    dia_vencimento = EXCLUDED.dia_vencimento,
    ativo          = EXCLUDED.ativo,
    atualizado_em  = NOW()
RETURNING id, nome, dias_semana, valor_mensal, dia_vencimento, ativo, criado_em, atualizado_em
`

type UpsertPlanoParams struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	Nome          string          `db:"nome" json:"nome"`
	DiasSemana    int32           `db:"dias_semana" json:"dias_semana"`
	ValorMensal   decimal.Decimal `db:"valor_mensal" json:"valor_mensal"`
	DiaVencimento int32           `db:"dia_vencimento" json:"dia_vencimento"`
	Ativo         bool            `db:"ativo" json:"ativo"`
}

func (q *Queries) UpsertPlano(ctx context.Context, arg UpsertPlanoParams) (Plano, error) {
	row := q.db.QueryRow(ctx, upsertPlano,
		arg.ID,
		arg.Nome,
		arg.DiasSemana,
		arg.ValorMensal,
		arg.DiaVencimento,
		arg.Ativo,
	)
	var i Plano
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.DiasSemana,
		&i.ValorMensal,
		&i.DiaVencimento,
		&i.Ativo,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
