// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: relatorio.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const frequenciaAtleta = `-- name: FrequenciaAtleta :one

SELECT
    COUNT(*) FILTER (WHERE f.presenca = 'PRESENTE')    ::bigint AS presentes,
    COUNT(*) FILTER (WHERE f.presenca = 'AUSENTE')     ::bigint AS ausentes,
    COUNT(*) FILTER (WHERE f.presenca = 'JUSTIFICADO') ::bigint AS justificados,
    COUNT(*)                                            ::bigint AS total
FROM frequencias f
JOIN treinos     t ON t.id = f.treino_id
WHERE f.atleta_id = $1
  AND t.data_treino BETWEEN $2 AND $3
`

type FrequenciaAtletaParams struct {
	AtletaID   uuid.UUID `db:"atleta_id" json:"atleta_id"`
	DataInicio time.Time `db:"data_inicio" json:"data_inicio"`
	DataFim    time.Time `db:"data_fim" json:"data_fim"`
}

type FrequenciaAtletaRow struct {
	Presentes    int64 `db:"presentes" json:"presentes"`
	Ausentes     int64 `db:"ausentes" json:"ausentes"`
	Justificados int64 `db:"justificados" json:"justificados"`
	Total        int64 `db:"total" json:"total"`
}

// ──────────────────────────────────────────────────────────────────────────────
// FREQUÊNCIA POR ATLETA
// ──────────────────────────────────────────────────────────────────────────────
// Agregado de presenças do atleta no período (somente treinos que tiveram
// frequência lançada). Não considera treinos sem lançamento como ausente.
func (q *Queries) FrequenciaAtleta(ctx context.Context, arg FrequenciaAtletaParams) (FrequenciaAtletaRow, error) {
	row := q.db.QueryRow(ctx, frequenciaAtleta, arg.AtletaID, arg.DataInicio, arg.DataFim)
	var i FrequenciaAtletaRow
	err := row.Scan(
		&i.Presentes,
		&i.Ausentes,
		&i.Justificados,
		&i.Total,
	)
	return i, err
}

const frequenciaTurmaPorAtleta = `-- name: FrequenciaTurmaPorAtleta :many
SELECT
    f.atleta_id,
    a.nome                                            AS atleta_nome,
    COUNT(*) FILTER (WHERE f.presenca = 'PRESENTE')    ::bigint AS presentes,
    COUNT(*) FILTER (WHERE f.presenca = 'AUSENTE')     ::bigint AS ausentes,
    COUNT(*) FILTER (WHERE f.presenca = 'JUSTIFICADO') ::bigint AS justificados,
    COUNT(*)                                            ::bigint AS total
FROM frequencias f
JOIN treinos     t ON t.id = f.treino_id
JOIN atletas     a ON a.id = f.atleta_id
WHERE t.turma_id = $1
  AND t.data_treino BETWEEN $2 AND $3
GROUP BY f.atleta_id, a.nome
ORDER BY a.nome
`

type FrequenciaTurmaPorAtletaParams struct {
	TurmaID    uuid.UUID `db:"turma_id" json:"turma_id"`
	DataInicio time.Time `db:"data_inicio" json:"data_inicio"`
	DataFim    time.Time `db:"data_fim" json:"data_fim"`
}

type FrequenciaTurmaPorAtletaRow struct {
	AtletaID     uuid.UUID `db:"atleta_id" json:"atleta_id"`
	AtletaNome   string    `db:"atleta_nome" json:"atleta_nome"`
	Presentes    int64     `db:"presentes" json:"presentes"`
	Ausentes     int64     `db:"ausentes" json:"ausentes"`
	Justificados int64     `db:"justificados" json:"justificados"`
	Total        int64     `db:"total" json:"total"`
}

// Resumo por atleta da turma no período.
func (q *Queries) FrequenciaTurmaPorAtleta(ctx context.Context, arg FrequenciaTurmaPorAtletaParams) ([]FrequenciaTurmaPorAtletaRow, error) {
	rows, err := q.db.Query(ctx, frequenciaTurmaPorAtleta, arg.TurmaID, arg.DataInicio, arg.DataFim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FrequenciaTurmaPorAtletaRow{}
	for rows.Next() {
		var i FrequenciaTurmaPorAtletaRow
		if err := rows.Scan(
			&i.AtletaID,
			&i.AtletaNome,
			&i.Presentes,
			&i.Ausentes,
			&i.Justificados,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInadimplencia = `-- name: ListInadimplencia :many

SELECT
    m.id,
    m.atleta_id,
    a.nome                                  AS atleta_nome,
    a.telefone                              AS atleta_telefone,
    a.email                                 AS atleta_email,
    m.competencia_ano,
    m.competencia_mes,
    m.data_vencimento,
    m.valor,
    m.status,
    (CURRENT_DATE - m.data_vencimento)::int AS dias_em_atraso
FROM mensalidades m
JOIN atletas      a ON a.id = m.atleta_id
WHERE m.status IN ('PENDENTE', 'VENCIDO')
  AND m.data_vencimento < CURRENT_DATE
  AND ($1::int IS NULL OR m.competencia_ano = $1)
  AND ($2::int IS NULL OR m.competencia_mes = $2)
  AND a.deletado_em IS NULL
ORDER BY m.data_vencimento
`

type ListInadimplenciaParams struct {
	Ano *int32 `db:"ano" json:"ano"`
	Mes *int32 `db:"mes" json:"mes"`
}

type ListInadimplenciaRow struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	AtletaID       uuid.UUID       `db:"atleta_id" json:"atleta_id"`
	AtletaNome     string          `db:"atleta_nome" json:"atleta_nome"`
	AtletaTelefone *string         `db:"atleta_telefone" json:"atleta_telefone"`
	AtletaEmail    *string         `db:"atleta_email" json:"atleta_email"`
	CompetenciaAno int32           `db:"competencia_ano" json:"competencia_ano"`
	CompetenciaMes int32           `db:"competencia_mes" json:"competencia_mes"`
	DataVencimento time.Time       `db:"data_vencimento" json:"data_vencimento"`
	Valor          decimal.Decimal `db:"valor" json:"valor"`
	Status         string          `db:"status" json:"status"`
	DiasEmAtraso   int32           `db:"dias_em_atraso" json:"dias_em_atraso"`
}

// ──────────────────────────────────────────────────────────────────────────────
// INADIMPLÊNCIA
// ──────────────────────────────────────────────────────────────────────────────
// Mensalidades em atraso (data_vencimento < hoje, status PENDENTE ou VENCIDO),
// com dados do atleta. Filtra opcionalmente por competência ano/mês.
func (q *Queries) ListInadimplencia(ctx context.Context, arg ListInadimplenciaParams) ([]ListInadimplenciaRow, error) {
	rows, err := q.db.Query(ctx, listInadimplencia, arg.Ano, arg.Mes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInadimplenciaRow{}
	for rows.Next() {
		var i ListInadimplenciaRow
		if err := rows.Scan(
			&i.ID,
			&i.AtletaID,
			&i.AtletaNome,
			&i.AtletaTelefone,
			&i.AtletaEmail,
			&i.CompetenciaAno,
			&i.CompetenciaMes,
			&i.DataVencimento,
			&i.Valor,
			&i.Status,
			&i.DiasEmAtraso,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumoInadimplencia = `-- name: ResumoInadimplencia :one
SELECT
    COUNT(*)::bigint                  AS total_mensalidades,
    COUNT(DISTINCT m.atleta_id)::bigint AS total_atletas,
    COALESCE(SUM(m.valor), 0)::numeric AS total_devido
FROM mensalidades m
JOIN atletas      a ON a.id = m.atleta_id
WHERE m.status IN ('PENDENTE', 'VENCIDO')
  AND m.data_vencimento < CURRENT_DATE
  AND ($1::int IS NULL OR m.competencia_ano = $1)
  AND ($2::int IS NULL OR m.competencia_mes = $2)
  AND a.deletado_em IS NULL
`

type ResumoInadimplenciaParams struct {
	Ano *int32 `db:"ano" json:"ano"`
	Mes *int32 `db:"mes" json:"mes"`
}

type ResumoInadimplenciaRow struct {
	TotalMensalidades int64           `db:"total_mensalidades" json:"total_mensalidades"`
	TotalAtletas      int64           `db:"total_atletas" json:"total_atletas"`
	TotalDevido       decimal.Decimal `db:"total_devido" json:"total_devido"`
}

// Totalizadores do mesmo recorte da consulta acima.
func (q *Queries) ResumoInadimplencia(ctx context.Context, arg ResumoInadimplenciaParams) (ResumoInadimplenciaRow, error) {
	row := q.db.QueryRow(ctx, resumoInadimplencia, arg.Ano, arg.Mes)
	var i ResumoInadimplenciaRow
	err := row.Scan(&i.TotalMensalidades, &i.TotalAtletas, &i.TotalDevido)
	return i, err
}

const totalTreinosTurma = `-- name: TotalTreinosTurma :one

SELECT COUNT(*)::bigint AS total
FROM treinos
WHERE turma_id = $1
  AND data_treino BETWEEN $2 AND $3
`

type TotalTreinosTurmaParams struct {
	TurmaID    uuid.UUID `db:"turma_id" json:"turma_id"`
	DataInicio time.Time `db:"data_inicio" json:"data_inicio"`
	DataFim    time.Time `db:"data_fim" json:"data_fim"`
}

// ──────────────────────────────────────────────────────────────────────────────
// FREQUÊNCIA CONSOLIDADA POR TURMA
// ──────────────────────────────────────────────────────────────────────────────
func (q *Queries) TotalTreinosTurma(ctx context.Context, arg TotalTreinosTurmaParams) (int64, error) {
	row := q.db.QueryRow(ctx, totalTreinosTurma, arg.TurmaID, arg.DataInicio, arg.DataFim)
	var total int64
	err := row.Scan(&total)
	return total, err
}
