// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: responsavel.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteResponsavel = `-- name: DeleteResponsavel :exec
DELETE FROM responsaveis
WHERE id = $1
`

func (q *Queries) DeleteResponsavel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResponsavel, id)
	return err
}

const despromoverPrincipalDoAtleta = `-- name: DespromoverPrincipalDoAtleta :exec
UPDATE responsaveis
SET contato_principal = FALSE,
    atualizado_em     = NOW()
WHERE atleta_id = $1
  AND contato_principal = TRUE
`

// Usado dentro da mesma transação do upsert quando o novo responsável vai
// ser marcado como principal. Sem WHERE id != $2 (vamos remover o antigo
// antes de inserir o novo, ou despromover todos antes do upsert).
func (q *Queries) DespromoverPrincipalDoAtleta(ctx context.Context, atletaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, despromoverPrincipalDoAtleta, atletaID)
	return err
}

const getPrincipalDoAtleta = `-- name: GetPrincipalDoAtleta :one
SELECT id, atleta_id, nome, cpf, email, telefone, parentesco, contato_principal, criado_em, atualizado_em
FROM responsaveis
WHERE atleta_id = $1
  AND contato_principal = TRUE
LIMIT 1
`

func (q *Queries) GetPrincipalDoAtleta(ctx context.Context, atletaID uuid.UUID) (Responsavel, error) {
	row := q.db.QueryRow(ctx, getPrincipalDoAtleta, atletaID)
	var i Responsavel
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.Telefone,
		&i.Parentesco,
		&i.ContatoPrincipal,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getResponsavelByCPF = `-- name: GetResponsavelByCPF :one
SELECT id, atleta_id, nome, cpf, email, telefone, parentesco, contato_principal, criado_em, atualizado_em
FROM responsaveis
WHERE cpf = $1
LIMIT 1
`

func (q *Queries) GetResponsavelByCPF(ctx context.Context, cpf *string) (Responsavel, error) {
	row := q.db.QueryRow(ctx, getResponsavelByCPF, cpf)
	var i Responsavel
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.Telefone,
		&i.Parentesco,
		&i.ContatoPrincipal,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getResponsavelByID = `-- name: GetResponsavelByID :one
SELECT id, atleta_id, nome, cpf, email, telefone, parentesco, contato_principal, criado_em, atualizado_em
FROM responsaveis
WHERE id = $1
`

func (q *Queries) GetResponsavelByID(ctx context.Context, id uuid.UUID) (Responsavel, error) {
	row := q.db.QueryRow(ctx, getResponsavelByID, id)
	var i Responsavel
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.Telefone,
		&i.Parentesco,
		&i.ContatoPrincipal,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listResponsaveisDoAtleta = `-- name: ListResponsaveisDoAtleta :many
SELECT id, atleta_id, nome, cpf, email, telefone, parentesco, contato_principal, criado_em, atualizado_em
FROM responsaveis
WHERE atleta_id = $1
ORDER BY contato_principal DESC, criado_em
`

func (q *Queries) ListResponsaveisDoAtleta(ctx context.Context, atletaID uuid.UUID) ([]Responsavel, error) {
	rows, err := q.db.Query(ctx, listResponsaveisDoAtleta, atletaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Responsavel{}
	for rows.Next() {
		var i Responsavel
		if err := rows.Scan(
			&i.ID,
			&i.AtletaID,
			&i.Nome,
			&i.Cpf,
			&i.Email,
			&i.Telefone,
			&i.Parentesco,
			&i.ContatoPrincipal,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResponsavel = `-- name: UpsertResponsavel :one
INSERT INTO responsaveis (
    id, atleta_id, nome, cpf, email, telefone, parentesco, contato_principal,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    nome              = EXCLUDED.nome,
    cpf               = EXCLUDED.cpf,
    email             = EXCLUDED.email,
    telefone          = EXCLUDED.telefone,
    parentesco        = EXCLUDED.parentesco,
    contato_principal = EXCLUDED.contato_principal,
    atualizado_em     = NOW()
RETURNING id, atleta_id, nome, cpf, email, telefone, parentesco, contato_principal, criado_em, atualizado_em
`

type UpsertResponsavelParams struct {
	ID               uuid.UUID `db:"id" json:"id"`
	AtletaID         uuid.UUID `db:"atleta_id" json:"atleta_id"`
	Nome             string    `db:"nome" json:"nome"`
	Cpf              *string   `db:"cpf" json:"cpf"`
	Email            *string   `db:"email" json:"email"`
	Telefone         string    `db:"telefone" json:"telefone"`
	Parentesco       string    `db:"parentesco" json:"parentesco"`
	ContatoPrincipal bool      `db:"contato_principal" json:"contato_principal"`
}

func (q *Queries) UpsertResponsavel(ctx context.Context, arg UpsertResponsavelParams) (Responsavel, error) {
	row := q.db.QueryRow(ctx, upsertResponsavel,
		arg.ID,
		arg.AtletaID,
		arg.Nome,
		arg.Cpf,
		arg.Email,
		arg.Telefone,
		arg.Parentesco,
		arg.ContatoPrincipal,
	)
	var i Responsavel
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.Nome,
		&i.Cpf,
		&i.Email,
		&i.Telefone,
		&i.Parentesco,
		&i.ContatoPrincipal,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
