// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: treinador.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countTreinadores = `-- name: CountTreinadores :one
SELECT COUNT(*)
FROM treinadores
WHERE deletado_em IS NULL
  AND ($1::text   IS NULL OR nome   ILIKE '%' || $1   || '%')
  AND ($2::text IS NULL OR status = $2)
`

type CountTreinadoresParams struct {
	Nome   *string `db:"nome" json:"nome"`
	Status *string `db:"status" json:"status"`
}

func (q *Queries) CountTreinadores(ctx context.Context, arg CountTreinadoresParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTreinadores, arg.Nome, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTreinadorByCPF = `-- name: GetTreinadorByCPF :one
SELECT id, usuario_id, nome, cpf, cref, telefone, status, criado_em, atualizado_em, deletado_em
FROM treinadores
WHERE cpf = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetTreinadorByCPF(ctx context.Context, cpf *string) (Treinador, error) {
	row := q.db.QueryRow(ctx, getTreinadorByCPF, cpf)
	var i Treinador
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nome,
		&i.Cpf,
		&i.Cref,
		&i.Telefone,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getTreinadorByID = `-- name: GetTreinadorByID :one
SELECT id, usuario_id, nome, cpf, cref, telefone, status, criado_em, atualizado_em, deletado_em
FROM treinadores
WHERE id = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetTreinadorByID(ctx context.Context, id uuid.UUID) (Treinador, error) {
	row := q.db.QueryRow(ctx, getTreinadorByID, id)
	var i Treinador
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nome,
		&i.Cpf,
		&i.Cref,
		&i.Telefone,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getTreinadorByUsuarioID = `-- name: GetTreinadorByUsuarioID :one
SELECT id, usuario_id, nome, cpf, cref, telefone, status, criado_em, atualizado_em, deletado_em
FROM treinadores
WHERE usuario_id = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetTreinadorByUsuarioID(ctx context.Context, usuarioID uuid.UUID) (Treinador, error) {
	row := q.db.QueryRow(ctx, getTreinadorByUsuarioID, usuarioID)
	var i Treinador
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nome,
		&i.Cpf,
		&i.Cref,
		&i.Telefone,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listTreinadores = `-- name: ListTreinadores :many
SELECT id, usuario_id, nome, cpf, cref, telefone, status, criado_em, atualizado_em, deletado_em
FROM treinadores
WHERE deletado_em IS NULL
  AND ($1::text   IS NULL OR nome   ILIKE '%' || $1   || '%')
  AND ($2::text IS NULL OR status = $2)
ORDER BY nome
LIMIT  $4
OFFSET $3
`

type ListTreinadoresParams struct {
	Nome   *string `db:"nome" json:"nome"`
	Status *string `db:"status" json:"status"`
	Off    int32   `db:"off" json:"off"`
	Lim    int32   `db:"lim" json:"lim"`
}

func (q *Queries) ListTreinadores(ctx context.Context, arg ListTreinadoresParams) ([]Treinador, error) {
	rows, err := q.db.Query(ctx, listTreinadores,
		arg.Nome,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Treinador{}
	for rows.Next() {
		var i Treinador
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Nome,
			&i.Cpf,
			&i.Cref,
			&i.Telefone,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTreinador = `-- name: SoftDeleteTreinador :exec
UPDATE treinadores
SET
    deletado_em   = NOW(),
    status        = 'INATIVO',
    atualizado_em = NOW()
WHERE id = $1
  AND deletado_em IS NULL
`

func (q *Queries) SoftDeleteTreinador(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTreinador, id)
	return err
}

const upsertTreinador = `-- name: UpsertTreinador :one
INSERT INTO treinadores (
    id, usuario_id, nome, cpf, cref, telefone, status,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    nome          = EXCLUDED.nome,
    cpf           = EXCLUDED.cpf,
    cref          = EXCLUDED.cref,
    telefone      = EXCLUDED.telefone,
    status        = EXCLUDED.status,
    atualizado_em = NOW()
RETURNING id, usuario_id, nome, cpf, cref, telefone, status, criado_em, atualizado_em, deletado_em
`

type UpsertTreinadorParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UsuarioID uuid.UUID `db:"usuario_id" json:"usuario_id"`
	Nome      string    `db:"nome" json:"nome"`
	Cpf       *string   `db:"cpf" json:"cpf"`
	Cref      *string   `db:"cref" json:"cref"`
	Telefone  *string   `db:"telefone" json:"telefone"`
	Status    string    `db:"status" json:"status"`
}

func (q *Queries) UpsertTreinador(ctx context.Context, arg UpsertTreinadorParams) (Treinador, error) {
	row := q.db.QueryRow(ctx, upsertTreinador,
		arg.ID,
		arg.UsuarioID,
		arg.Nome,
		arg.Cpf,
		arg.Cref,
		arg.Telefone,
		arg.Status,
	)
	var i Treinador
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nome,
		&i.Cpf,
		&i.Cref,
		&i.Telefone,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
