// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: treino.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTreinosPorTurma = `-- name: CountTreinosPorTurma :one
SELECT COUNT(*)
FROM treinos
WHERE turma_id = $1
  AND ($2::date IS NULL OR data_treino >= $2)
  AND ($3::date    IS NULL OR data_treino <= $3)
`

type CountTreinosPorTurmaParams struct {
	TurmaID    uuid.UUID  `db:"turma_id" json:"turma_id"`
	DataInicio *time.Time `db:"data_inicio" json:"data_inicio"`
	DataFim    *time.Time `db:"data_fim" json:"data_fim"`
}

func (q *Queries) CountTreinosPorTurma(ctx context.Context, arg CountTreinosPorTurmaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTreinosPorTurma, arg.TurmaID, arg.DataInicio, arg.DataFim)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTreinoByID = `-- name: GetTreinoByID :one
SELECT id, turma_id, data_treino, hora_inicio, hora_fim, observacao, criado_em
FROM treinos
WHERE id = $1
`

func (q *Queries) GetTreinoByID(ctx context.Context, id uuid.UUID) (Treino, error) {
	row := q.db.QueryRow(ctx, getTreinoByID, id)
	var i Treino
	err := row.Scan(
		&i.ID,
		&i.TurmaID,
		&i.DataTreino,
		&i.HoraInicio,
		&i.HoraFim,
		&i.Observacao,
		&i.CriadoEm,
	)
	return i, err
}

const getTreinoByTurmaData = `-- name: GetTreinoByTurmaData :one
SELECT id, turma_id, data_treino, hora_inicio, hora_fim, observacao, criado_em
FROM treinos
WHERE turma_id = $1
  AND data_treino = $2
LIMIT 1
`

type GetTreinoByTurmaDataParams struct {
	TurmaID    uuid.UUID `db:"turma_id" json:"turma_id"`
	DataTreino time.Time `db:"data_treino" json:"data_treino"`
}

func (q *Queries) GetTreinoByTurmaData(ctx context.Context, arg GetTreinoByTurmaDataParams) (Treino, error) {
	row := q.db.QueryRow(ctx, getTreinoByTurmaData, arg.TurmaID, arg.DataTreino)
	var i Treino
	err := row.Scan(
		&i.ID,
		&i.TurmaID,
		&i.DataTreino,
		&i.HoraInicio,
		&i.HoraFim,
		&i.Observacao,
		&i.CriadoEm,
	)
	return i, err
}

const listTreinosPorTurma = `-- name: ListTreinosPorTurma :many
SELECT id, turma_id, data_treino, hora_inicio, hora_fim, observacao, criado_em
FROM treinos
WHERE turma_id = $1
  AND ($2::date IS NULL OR data_treino >= $2)
  AND ($3::date    IS NULL OR data_treino <= $3)
ORDER BY data_treino DESC
LIMIT  $5
OFFSET $4
`

type ListTreinosPorTurmaParams struct {
	TurmaID    uuid.UUID  `db:"turma_id" json:"turma_id"`
	DataInicio *time.Time `db:"data_inicio" json:"data_inicio"`
	DataFim    *time.Time `db:"data_fim" json:"data_fim"`
	Off        int32      `db:"off" json:"off"`
	Lim        int32      `db:"lim" json:"lim"`
}

func (q *Queries) ListTreinosPorTurma(ctx context.Context, arg ListTreinosPorTurmaParams) ([]Treino, error) {
	rows, err := q.db.Query(ctx, listTreinosPorTurma,
		arg.TurmaID,
		arg.DataInicio,
		arg.DataFim,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Treino{}
	for rows.Next() {
		var i Treino
		if err := rows.Scan(
			&i.ID,
			&i.TurmaID,
			&i.DataTreino,
			&i.HoraInicio,
			&i.HoraFim,
			&i.Observacao,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTreino = `-- name: UpsertTreino :one
INSERT INTO treinos (
    id, turma_id, data_treino, hora_inicio, hora_fim, observacao, criado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (turma_id, data_treino) DO UPDATE SET
    hora_inicio = EXCLUDED.hora_inicio,
    hora_fim    = EXCLUDED.hora_fim,
    observacao  = EXCLUDED.observacao
RETURNING id, turma_id, data_treino, hora_inicio, hora_fim, observacao, criado_em
`

type UpsertTreinoParams struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	TurmaID    uuid.UUID   `db:"turma_id" json:"turma_id"`
	DataTreino time.Time   `db:"data_treino" json:"data_treino"`
	HoraInicio pgtype.Time `db:"hora_inicio" json:"hora_inicio"`
	HoraFim    pgtype.Time `db:"hora_fim" json:"hora_fim"`
	Observacao *string     `db:"observacao" json:"observacao"`
}

func (q *Queries) UpsertTreino(ctx context.Context, arg UpsertTreinoParams) (Treino, error) {
	row := q.db.QueryRow(ctx, upsertTreino,
		arg.ID,
		arg.TurmaID,
		arg.DataTreino,
		arg.HoraInicio,
		arg.HoraFim,
		arg.Observacao,
	)
	var i Treino
	err := row.Scan(
		&i.ID,
		&i.TurmaID,
		&i.DataTreino,
		&i.HoraInicio,
		&i.HoraFim,
		&i.Observacao,
		&i.CriadoEm,
	)
	return i, err
}
