// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: turma.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTurmas = `-- name: CountTurmas :one
SELECT COUNT(*)
FROM turmas
WHERE deletado_em IS NULL
  AND ($1::text   IS NULL OR nome   ILIKE '%' || $1   || '%')
  AND ($2::text IS NULL OR status = $2)
`

type CountTurmasParams struct {
	Nome   *string `db:"nome" json:"nome"`
	Status *string `db:"status" json:"status"`
}

func (q *Queries) CountTurmas(ctx context.Context, arg CountTurmasParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTurmas, arg.Nome, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHorariosByTurma = `-- name: DeleteHorariosByTurma :exec
DELETE FROM horarios_turma WHERE turma_id = $1
`

func (q *Queries) DeleteHorariosByTurma(ctx context.Context, turmaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHorariosByTurma, turmaID)
	return err
}

const getTurmaByID = `-- name: GetTurmaByID :one
SELECT id, nome, faixa_etaria_min, faixa_etaria_max, capacidade_max, treinador_id, campo_id, status, criado_em, atualizado_em, deletado_em
FROM turmas
WHERE id = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetTurmaByID(ctx context.Context, id uuid.UUID) (Turma, error) {
	row := q.db.QueryRow(ctx, getTurmaByID, id)
	var i Turma
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.FaixaEtariaMin,
		&i.FaixaEtariaMax,
		&i.CapacidadeMax,
		&i.TreinadorID,
		&i.CampoID,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const insertHorarioTurma = `-- name: InsertHorarioTurma :exec
INSERT INTO horarios_turma (id, turma_id, dia_semana, hora_inicio, hora_fim)
VALUES ($1, $2, $3, $4, $5)
`

type InsertHorarioTurmaParams struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	TurmaID    uuid.UUID   `db:"turma_id" json:"turma_id"`
	DiaSemana  string      `db:"dia_semana" json:"dia_semana"`
	HoraInicio pgtype.Time `db:"hora_inicio" json:"hora_inicio"`
	HoraFim    pgtype.Time `db:"hora_fim" json:"hora_fim"`
}

func (q *Queries) InsertHorarioTurma(ctx context.Context, arg InsertHorarioTurmaParams) error {
	_, err := q.db.Exec(ctx, insertHorarioTurma,
		arg.ID,
		arg.TurmaID,
		arg.DiaSemana,
		arg.HoraInicio,
		arg.HoraFim,
	)
	return err
}

const listHorariosPorTurma = `-- name: ListHorariosPorTurma :many
SELECT id, turma_id, dia_semana, hora_inicio, hora_fim
FROM horarios_turma
WHERE turma_id = $1
ORDER BY dia_semana, hora_inicio
`

func (q *Queries) ListHorariosPorTurma(ctx context.Context, turmaID uuid.UUID) ([]HorariosTurma, error) {
	rows, err := q.db.Query(ctx, listHorariosPorTurma, turmaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HorariosTurma{}
	for rows.Next() {
		var i HorariosTurma
		if err := rows.Scan(
			&i.ID,
			&i.TurmaID,
			&i.DiaSemana,
			&i.HoraInicio,
			&i.HoraFim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurmas = `-- name: ListTurmas :many
SELECT id, nome, faixa_etaria_min, faixa_etaria_max, capacidade_max, treinador_id, campo_id, status, criado_em, atualizado_em, deletado_em
FROM turmas
WHERE deletado_em IS NULL
  AND ($1::text   IS NULL OR nome   ILIKE '%' || $1   || '%')
  AND ($2::text IS NULL OR status = $2)
ORDER BY nome
LIMIT  $4
OFFSET $3
`

type ListTurmasParams struct {
	Nome   *string `db:"nome" json:"nome"`
	Status *string `db:"status" json:"status"`
	Off    int32   `db:"off" json:"off"`
	Lim    int32   `db:"lim" json:"lim"`
}

func (q *Queries) ListTurmas(ctx context.Context, arg ListTurmasParams) ([]Turma, error) {
	rows, err := q.db.Query(ctx, listTurmas,
		arg.Nome,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turma{}
	for rows.Next() {
		var i Turma
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.FaixaEtariaMin,
			&i.FaixaEtariaMax,
			&i.CapacidadeMax,
			&i.TreinadorID,
			&i.CampoID,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTurma = `-- name: SoftDeleteTurma :exec
UPDATE turmas
SET
    deletado_em   = NOW(),
    status        = 'ENCERRADA',
    atualizado_em = NOW()
WHERE id = $1
  AND deletado_em IS NULL
`

func (q *Queries) SoftDeleteTurma(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTurma, id)
	return err
}

const upsertTurma = `-- name: UpsertTurma :one
INSERT INTO turmas (
    id, nome, faixa_etaria_min, faixa_etaria_max, capacidade_max,
    treinador_id, campo_id, status,
    criado_em, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE SET
    nome             = EXCLUDED.nome,
    faixa_etaria_min = EXCLUDED.faixa_etaria_min,
    faixa_etaria_max = EXCLUDED.faixa_etaria_max,
    capacidade_max   = EXCLUDED.capacidade_max,
    treinador_id     = EXCLUDED.treinador_id,
    campo_id         = EXCLUDED.campo_id,
    status           = EXCLUDED.status,
    atualizado_em    = NOW()
RETURNING id, nome, faixa_etaria_min, faixa_etaria_max, capacidade_max, treinador_id, campo_id, status, criado_em, atualizado_em, deletado_em
`

type UpsertTurmaParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	Nome           string     `db:"nome" json:"nome"`
	FaixaEtariaMin int32      `db:"faixa_etaria_min" json:"faixa_etaria_min"`
	FaixaEtariaMax int32      `db:"faixa_etaria_max" json:"faixa_etaria_max"`
	CapacidadeMax  int32      `db:"capacidade_max" json:"capacidade_max"`
	TreinadorID    *uuid.UUID `db:"treinador_id" json:"treinador_id"`
	CampoID        *uuid.UUID `db:"campo_id" json:"campo_id"`
	Status         string     `db:"status" json:"status"`
}

func (q *Queries) UpsertTurma(ctx context.Context, arg UpsertTurmaParams) (Turma, error) {
	row := q.db.QueryRow(ctx, upsertTurma,
		arg.ID,
		arg.Nome,
		arg.FaixaEtariaMin,
		arg.FaixaEtariaMax,
		arg.CapacidadeMax,
		arg.TreinadorID,
		arg.CampoID,
		arg.Status,
	)
	var i Turma
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.FaixaEtariaMin,
		&i.FaixaEtariaMax,
		&i.CapacidadeMax,
		&i.TreinadorID,
		&i.CampoID,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
