// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: uniforme.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getUniformeByAtleta = `-- name: GetUniformeByAtleta :one
SELECT id, atleta_id, tam_camisa, tam_short, tam_chuteira, atualizado_em
FROM uniformes
WHERE atleta_id = $1
`

func (q *Queries) GetUniformeByAtleta(ctx context.Context, atletaID uuid.UUID) (Uniforme, error) {
	row := q.db.QueryRow(ctx, getUniformeByAtleta, atletaID)
	var i Uniforme
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.TamCamisa,
		&i.TamShort,
		&i.TamChuteira,
		&i.AtualizadoEm,
	)
	return i, err
}

const upsertUniforme = `-- name: UpsertUniforme :one
INSERT INTO uniformes (
    id, atleta_id, tam_camisa, tam_short, tam_chuteira, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (atleta_id) DO UPDATE SET
    tam_camisa    = EXCLUDED.tam_camisa,
    tam_short     = EXCLUDED.tam_short,
    tam_chuteira  = EXCLUDED.tam_chuteira,
    atualizado_em = NOW()
RETURNING id, atleta_id, tam_camisa, tam_short, tam_chuteira, atualizado_em
`

type UpsertUniformeParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	AtletaID    uuid.UUID `db:"atleta_id" json:"atleta_id"`
	TamCamisa   string    `db:"tam_camisa" json:"tam_camisa"`
	TamShort    string    `db:"tam_short" json:"tam_short"`
	TamChuteira string    `db:"tam_chuteira" json:"tam_chuteira"`
}

// Upsert por atleta_id (constraint uq_uniformes_atleta). Mantém ID estável
// mesmo em updates: ON CONFLICT (atleta_id) preserva o id existente.
func (q *Queries) UpsertUniforme(ctx context.Context, arg UpsertUniformeParams) (Uniforme, error) {
	row := q.db.QueryRow(ctx, upsertUniforme,
		arg.ID,
		arg.AtletaID,
		arg.TamCamisa,
		arg.TamShort,
		arg.TamChuteira,
	)
	var i Uniforme
	err := row.Scan(
		&i.ID,
		&i.AtletaID,
		&i.TamCamisa,
		&i.TamShort,
		&i.TamChuteira,
		&i.AtualizadoEm,
	)
	return i, err
}
