// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: usuario.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, email, senha_hash, perfil, ativo, criado_em, atualizado_em, deletado_em
FROM usuarios
WHERE email = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.Perfil,
		&i.Ativo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getUsuarioByID = `-- name: GetUsuarioByID :one
SELECT id, email, senha_hash, perfil, ativo, criado_em, atualizado_em, deletado_em
FROM usuarios
WHERE id = $1
  AND deletado_em IS NULL
`

func (q *Queries) GetUsuarioByID(ctx context.Context, id uuid.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioByID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.Perfil,
		&i.Ativo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
