---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: realtpmsys-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    secretToken: AgAFsRS5F/GsqGON85g1nG+FVDgj3zFEQ0/OlRDNIImbQwHwCBEP7QbJQF8IanbcTIn32AMBzyGoWdBFxwbfeKcMGiMRuki+MhTe7LeMHxVQbVfoyVB5GeRIZ8FZPiGRZP1Bnp6bGGMlLKDlZqsKXfxvWh+YVqt8ZKFyHOX+kRKwJo90KUIfcWzTtOpbwYycEnUQgcOgNoE/usgmMgurRpt2/0TXrOntVowfVdJIdv4eOULbI7QDAOXLjwc7DTSX4Tus5E4dfYS3zgUe1fcY69CXyEQjX9HY/egokl58reT/6+iMSHlaoZ7lnW9LAKkdWKpvGKUyRvEd5Ekvf8kxAFV8A3WlQMoAYHTKw8jtcIJY0qYHgiUXpzpg86Wl9GSO8DFzMZjEcdHWw2kFfawyHujZGQAfTv0U5W07LJvJWb03lvp4udoyJdgFmSUa0Y8ZF+Ji8hbKPpDVZ43bfvRE96whbPYSk+fZuoFjNrDxrGbdmSR4tL5cbScxr7vdHmVNYhZvVudx/7gTlBzaZfq2CVlTC6pwjwgWbMCjRaylgw0rj4UAllWRVcEwf82E6vLeigfkLPe792qxwo1/8bsyU5IBP2xEuo/GYxHEr3ensaFIuwbPgi8ibSBwMHCNVbQeuLvD7fyuSz7il0njldYI3cgGr9oW1sXoH9iL9BpO7kM5tKgwn08p28lFvCkJ+VNw3YVHJTaaOgKiBE8bUFLt6qcZ59MYrEOwRcB2NVLmDnC9su7Y5QhOFRomPJD5uw==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ci-secret
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: realtpmsys-tekton
        app.kubernetes.io/part-of: realtpmsys
        environment: dev
        lab_id: lab-k8s-01
        lab_owner: jose.mussauer
      name: realtpmsys-webhook-secret
      namespace: cicd
    type: Opaque
