---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: realtpmsys-secrets
  namespace: realtpmsys
spec:
  encryptedData:
    jwt-secret: AgBMbcfFOC68XCkgVuAdwJgpAQuT99B7IDr5a9Fwwsjm/0S8lJmnbWJFb4xB27cHvedFByjy3++yRtahW37coJPuSY6kJpjM7oit6EmM1xotOwxSbh2CxPq4PGQrC2mUpWEep+XX23irPJFwixa20WIDI9TGeJ6hG2vYuFif+/3E+HC7ULwHWSn8yaK5J0i6CsFftEWRbamdU4SAYGxBpFzw9fFzr92cgx082Gp/OibdlNrGOcMWo1ggovg9pmlGSLpbeYpbxxLirzU1QNKxIOqqCyUwfMMoutreOErMatdV6wLylF/odA8Ebb2EtKpvjPy4bUXrJcsxctTcyOOaBnWkMrUVKtZuYl9qhB0Mq3qZGmOZ3910C4EuTLP5zwbko8Dp8YgmVh2nS7twggaPSKZkZSLjV1thce/EZ4hklHP1opIbuQeThYGzinW7Eu6zi4/qS/Wrpf5rI0NCsO9rk7zZ2ccXrJcX4ysQ50J9NaAax6uLrpy2UP8PN1nmXD3xB/0U3UpC4hawE8lupiGAprAE9jviFz3FXbokWHE7j9AUCZm3OILvpfKiegehHJLAJqg5guZumK/zoeG83QIyhSLNCh8hELgQYxQ+WyCwdArneK4ykhKLTga66CO4Sb96SGbeGwmdPdshOENexF83vGeSeClyrdHF47fHQkjLRcqZouU+0BxR7iEJi744VoJ5ac5Ql4sqzzM/gObQDGUt3Um6EFeRKiLFHdQr8UtzFarWapWsF1bkBs4JEvY+d7mQOhHEXzZ0DjcryF9AgfDKogLd
    pg-password: AgBQY/8+nHDvYGdbchiuPfyHRHFfYu9MYb/vdl0mmLutern+wNWBceDzm3jkByU5QNX68Pkgx40G8g5hmXJB0f4yynd6/xhphlWO94VIwlVxCKxg4tPo0X+YFiVJCNJLZQtNshLTzPFruugz4aHGvYXhfeHI8pdeJ8/GE13Nkocjh5qQvVWTYC8O8Z0L+B7NAT5asOu4foGHMijrCeSxnLEQzPyC6j9pprspfy0WMycw0bflYj7CTDB8QHTqJavIJosDthdprDyvX/h3QSxhA3026PsBjtO5t8zOUjFoE9/qTjFaFdydE1v+vzyRFMFYA+bAiHnIJ2+MCt4k1OTmJky3K2nSN+hqEHV5WoI6yFr9XCE2iBmSsS6mWs+aRdDWVer+QO7hK+RNZtCrwTMc4hyZFFoCtlo6tUFIUtPUrJSJ7s7FthWN5rUDpsS5+p0ZK0SrsFce8O3jvCwtBTGHmm90RrHqqleHwHMZ3NheNuVN79FTA1d4x901lt4qIc8igaSnwc50JbOvVjgxvJLIeJzrR7kii0EF5RsVepCiPQTVDYkJuC/FlLFo5jMNhYVy59U2ULABhB3+ckWWERbvy5nXiHGAneVOSZRoaj+7gCqS1qaA95ZZnPQxL8BYvRBXR7s6d25bp2eLxLJROLTpi4iBH5YfZPR5IUMtYz0o7vyOJ0zQQOjwb0uh+GxKROcgE0k1tqHgO8pOZMldbiAssA==
  template:
    metadata:
      labels:
        app.kubernetes.io/component: config
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: realtpmsys
        environment: dev
        lab_id: lab-k8s-01
        lab_owner: jose.mussauer
      name: realtpmsys-secrets
      namespace: realtpmsys
    type: Opaque
